### ISSUE TITLE
地点确定了吗？

### ISSUE THREAD

**Issue by zhouzhongyuan** [baixing/BXT#1]

**Comment by xu-yanfei** [comment]
呀抱歉～～我猜您是报名晚了我们没有来得及通知？
地点在交大校园里，截止到今天上午报名的同学我们都有加微信群在群里通知的，再晚的就没能来得及了。
讲座内容会整理好后在这个repo里贴出来的。我们可以继续线上交流。

**Comment by zhouzhongyuan** [comment]
恩那 我是下午才报名的！ 希望下次有机会再去吧
