### ISSUE TITLE
[BXT-009] 《使用 RxJS 抽象业务逻辑》 by 徐飞

### ISSUE THREAD

**Issue by hax** [baixing/BXT#10]
# 使用 RxJS 抽象业务逻辑

### 本期讲师

![avatar](https://cloud.githubusercontent.com/assets/159840/20593809/ad919e28-b26e-11e6-9738-8d74d7c02e41.jpg)

**徐飞**

徐飞，网名 “民工精髓V”，曾任苏宁云计算中心、Teambition 前端架构师，有十多年大型企业应用前端架构经验，国内权威的 AngularJS 专家，知乎上前端开发、前端工程师、JavaScript 等话题优秀回答者，“神棍” 级的技术预言家，业内尊称 “民工叔叔”。

### 本期主题

RxJS 是 ReactiveX 在 JavaScript 下的实现。它用于描述数据变化与时间的关系，是异步操作的有效工具。本期沙龙邀请到前端架构师徐飞，为大家带来 RxJS 在前端业务架构中的实践心得。

### 本期具体安排

* 时间：2016 年 11 月 29 日（周二） 晚 7:30～9:00
* 地点：上海市徐汇区交通大学内
* 参加对象：工程师
* 活动名额：50 人

***

### 本期内容小结

* 请参考：[流动的数据——使用 RxJS 构造复杂单页应用的数据逻辑](https://zhuanlan.zhihu.com/p/23305264)

**Comment by ccpend** [comment]
期待！

**Comment by Liyuk** [comment]
神棍级！话说有直播么。

**Comment by JasinYip** [comment]
会有视频或者文字版之类的分享到网上吗？

**Comment by cssmagic** [comment]
@Liyuk 
抱歉，本期没有直播。

@JasinYip 
正在联系讲师，请稍等。回头会来更新的。

**Comment by cssmagic** [comment]
@JasinYip 
原帖已更新。请参考末尾的链接。
