### ISSUE TITLE
[BXT-010]《共享单车违章停车的大数据计算——全栈数据分析实践》by 周宁奕

### ISSUE THREAD

**Issue by hax** [baixing/BXT#11]
# 全栈数据分析实战：共享单车违章停车的大数据计算

### 本期讲师

![avatar](https://cloud.githubusercontent.com/assets/159840/25525493/b6201cc0-2c41-11e7-8b6f-971113b3bede.png)

**周宁奕**

网名野兽，设计师转码农，糊涂画板独立开发者、撰稿人、数据爱好者，在阿里云做过3年数据可视化(WebGIS、WebGL为主)，现在众安保险负责数据科学前端团队

### 本期主题

前端工程师技术的边界也越来越宽广，除了适应越来越快的变化和越来越宽的领域，数据相关的工程师值得在数据上下游链路上拓宽广度。本次分享以摩拜单车的抓取与可视化为case，介绍nodejs爬虫、postgres分析、leaflet与QGIS的数据可视化的技术和思路。

1、爬虫与相关技术(Nodejs、Charles、Postgres)
2、数据可视化相关技术(leaflet、QGIS)
3、社会学背景知识
4、延伸，一些其他的实践

### 本期具体安排

* 时间：2017 年 5 月 4 日（周四）晚 7:00～9:00
* 地点：上海市徐汇区交通大学内
* 参加对象：工程师
* 活动名额：50人

### 报名

follow me: http://www.hdb.com/party/zvaqb.html

**Comment by MAYDAY1993** [comment]
简直激动 貌似从去年star开始就没收到新的通知 这次还是野兽 期待
