### ISSUE TITLE
[BXT-011] 《TypeScript 语言的进化》 by 吴名扬

### ISSUE THREAD

**Issue by hax** [baixing/BXT#13]
# TypeScript 语言的进化

### 本期讲师

![吴名扬](https://user-images.githubusercontent.com/159840/28764574-c586e2f6-75f8-11e7-8846-8548311adc35.jpg)

**吴名扬**

TypeScript、VueJS 等项目贡献者，常于前端开源社区投 patch 报 bug。TypeScript 2.2 中 object type 的实现者，VueJS贡献者，基于 TypeScript 的 VueJS编辑器插件Vetur的维护者之一。Vim用户。前百姓网工程师，现就职于美屋得信息技术（上海）有限公司。

### 本期主题

TypeScript 是众多编译到JavaScript语言中的佼佼者。自版本 1.0 到如今的 2.4，逐渐增加特性，慢慢进化出一套为 JavaScript 度身定制的类型系统，并拥有不亚于学术语言的强大和表现力。同时 TypeScript 也具有非常稳固的实现。本期沙龙我们邀请到了 TypeScript 社区的活跃贡献者吴名扬，带我们回顾 TypeScript 的发展历程和里程碑，比较与其他 AltJS 如 CoffeeScript、Flow 等的异同，探讨 TypeScript 的设计理念和语言特色，介绍其扩展性和工具链，展望其未来的发展方向。

### 本期具体安排

* 时间：2017 年 8 月 8 日（周二）晚 7:00～9:00
* 地点：上海市徐汇区交通大学内
* 参加对象：TypeScript/JavaScript 程序员，编程语言爱好者
* 活动名额：~~50~~ 80 人

### 报名

~~稍后放出报名链接……~~
报名链接来了：
http://www.hdb.com/party/lu0wb.html

本次活动在线直播：
https://www.douyu.com/1238829

**Comment by MAYDAY1993** [comment]
沙发～

**Comment by z5** [comment]
期待！

**Comment by hax** [comment]
报名链接出来了。

**Comment by printjs** [comment]
很好，我在成都

**Comment by 1xuanyuan1** [comment]
报名···

**Comment by zyg-github** [comment]
这么快就满了。。。。
回播吗？

**Comment by MAYDAY1993** [comment]
@zyg-github  又开了十个名额

**Comment by cssmagic** [comment]
以前每次筹备 BXT 技术沙龙，外地同学都说不开心，上海同学都说席位少，于是……

**本期终于有直播了**！今晚七点见，点此直达直播间： http://www.douyu.com/1238829 （大家如果有斗鱼账号的话，可以先加关注。以后就可以收到开播提醒了。）
