### ISSUE TITLE
[BXT-013] 《代码性能优化的几点建议》 by 赵劼

### ISSUE THREAD

**Issue by hax** [baixing/BXT#17]
# 代码性能优化的几点建议

### 本期讲师

**赵劼**

![zhaojie](https://user-images.githubusercontent.com/159840/31806946-d4b4ddd8-b530-11e7-8344-f1d7519fdb8b.png)

赵劼，网名老赵，洋名Jeffrey Zhao，又称赵姐夫，知乎“温赵轮”三大软狗之一。常年热爱编程，热爱开源。对于各类编程语言，虚拟机，编译器的使用及优化有着浓厚的兴趣，对程序员能力与修养等相关问题也有着浓厚的兴趣，非常希望能够写程序到60岁。

老赵是多年微软 MVP，曾供职于盛大创新院，后投身 IBM，实现了从互联网架构向传统企业开发的“退化”。近六年来任职于摩根大通投资银行核心技术部，目前主要参与公司内部交易平台的开发与框架设计，有幸逐渐成为团队中唯一将大部分时间投身于系统性能优化的技术人员，在基于 .NET 平台的代码性能优化上积累了丰富的实践经验。

工作之余，主要兴趣为弹琴及做饭，立志为彰显码农正面形象做出贡献。近月喜得一女，经常为其哭闹而烦恼。

### 本期主题

由于各种原因，似乎大部分程序员更多地在关注系统快速开发，而对产生的性能问题则忽略不计，直至攒下的技术债统一爆发，造成不可挽回的结果。本人有幸在过去几年中获得充分的机会对大量 .NET 代码进行观察，发现其中的性能问题，并进行有针对性的优化。趁此机会，想对过去几年内积攒下来的经验进行简单的总结。

本次分享的具体细节主要基于 .NET 平台，但方法和思路是通用的，所以欢迎各语言平台的程序员前来面基。

### 本期具体安排

* 时间：2017 年 10 月 25 日（周三）晚 7:30～9:00
* 地点：上海市徐汇区交通大学内
* 参加对象：程序员
* 活动名额：50 人

### 报名

（已结束）

### 直播

斗鱼直播间：http://www.douyu.com/1238829

**Comment by zpbx** [comment]
幻灯片：
http://zhaojie.me/dotnet-perf/slides/index.html#/
