### ISSUE TITLE
[BXT-014] 《如何打造一个JS平台下通用的 microbenchmark 轮子》 by 贺师俊（Hax）

### ISSUE THREAD

**Issue by hax** [baixing/BXT#19]
# 如何打造一个JS平台下通用的 microbenchmark 轮子

### 本期讲师

![avatar](https://cloud.githubusercontent.com/assets/5830104/15106449/05f5b55a-15fc-11e6-9218-557db24c5b45.jpg)

贺师俊（Hax）

百姓网架构部工程师。

### 本期主题

随着 JavaScript 生态的日益成熟，库、框架、组件的竞争越来越注重性能，而性能比较需要可靠的基准测试。另一方面，工程师在进行性能调优时也深入到了代码级的微优化。但 JavaScript 引擎不断进化，过去的经验今天未必适用。到底哪个快？要**测**，不能靠**猜**。

本次分享将探讨在 JavaScript 平台下进行微基准测试需要注意的问题，并通过**现场撸码**的方式，展示如何从零开始打造一个全平台通用、可靠且（比老牌的 Benchmark.js 更）好用的微基准测试（microbenchmark）支持库，并顺带演示相关的开发语言（TypeScript）和开发工具的运用。

【说明】本次分享是上个月 hax 在北京的两次同主题分享的升级版，内容有不少更新。12 月 16 日的 D2 活动也会分享这一主题，但受限于时间，不会采用现场撸码的形式。

### 本期具体安排

- 时间：2017 年 12 月 14 日（周四） 19:30～21:30
- 地点：上海市徐汇区·上海交通大学·浩然高科技大厦
- 参加对象：TypeScript/JavaScript 程序员，Web 前端工程师，Node.js 工程师
- 活动名额：50 人

### 报名

报名链接：http://www.hdb.com/party/96152.html

### 直播

斗鱼直播：https://www.douyu.com/hax

**Comment by myst729** [comment]
可以可以，等直播

**Comment by akira-cn** [comment]
等直播+1

**Comment by Lellansin** [comment]
已报名， @myst729  一起？

**Comment by galenyuan** [comment]
@Lellansin 开个直播

**Comment by wynn5a** [comment]
等直播。。。

**Comment by hax** [comment]
本次直播网址： https://www.douyu.com/hax

**Comment by AuthorJim** [comment]
浩然大厦几楼？

**Comment by penouc** [comment]
666
