### ISSUE TITLE
[BXT-001] 《重拾 CSS 的乐趣》 by CSS魔法

### ISSUE THREAD

**Issue by cssmagic** [baixing/BXT#2]
# 重拾 CSS 的乐趣
### 本期讲师

[![avatar](https://cloud.githubusercontent.com/assets/1231359/9621951/f2248490-515f-11e5-81fb-a3f410cd0312.jpg)](https://github.com/cssmagic)

CSS魔法 (@cssmagic)
- 百姓网前端工程师
- 移动 Web UI 框架 CMUI 作者
- 自称 “披着前端工程师外衣的设计师”

（ [微博](http://weibo.com/cssmagic) &nbsp;|&nbsp; [GitHub](https://github.com/cssmagic) &nbsp;|&nbsp; [知乎](http://www.zhihu.com/people/cssmagic) ）
### 本期演讲简介

在你的头脑里，CSS 是什么？是一团枯燥的代码，还是一堆乏味的工具？在与项目进度日复一日的缠斗中，我们是否早已遗忘了 CSS 最初带给我们的欣喜？

百姓网的 “CSS魔法” 同学尝试找寻这份遗失的感动。在他的演讲中，有真实的网页案例，有纯粹好玩的技巧，更有乍看起来完全不可能用 CSS 实现的神奇效果；他将在你的惊叹声中探索 CSS 所能达到的极致，一起重拾 CSS 的乐趣。

![pic](https://cloud.githubusercontent.com/assets/1231359/9621972/23ca9746-5160-11e5-987c-ff74064eda9e.jpg)
### 本期具体安排
- 时间：2015年9月1日（周二） 晚7:30
- 地点：上海市徐汇区交通大学内
- 参加对象：对前端感兴趣的工程师们
- 活动名额：50人

---
### 本期幻灯片
- [[幻灯片] 重拾 CSS 的乐趣（上）](https://github.com/cssmagic/blog/issues/52)
- [[幻灯片] 重拾 CSS 的乐趣（下）](https://github.com/cssmagic/blog/issues/54)
### 本期视频
- [BXT-001：重拾 CSS 的乐趣](http://www.imooc.com/learn/588) （需要慕课网账号）

**Comment by cssmagic** [comment]
## 本期 Demo 时间

### CSS Modules 的原理与实践

> by @fraserxu
- 理念
  - [CSS Modules 介绍文章](http://glenmaddern.com/articles/css-modules)
- 实践
  - [CSS Modules Webpack Demo](https://github.com/css-modules/webpack-demo)
  - [CSS Loader for Webpack](https://github.com/webpack/css-loader)

### GDG 活动通知

> by @yzpower
- [2015中国国际乐器展览会网络音乐应用创新开发竞赛](http://chinagdg.org/2015/08/5881/)
  - 活动时间：2015.09.01 ～ 2015.10.16

**Comment by snaketzy** [comment]
感谢分享，topic很棒

**Comment by yzpower** [comment]
GDG活动：
2015中国国际乐器展览会网络音乐应用创新开发竞赛 – 请大家踊跃参加！
http://chinagdg.org/2015/08/5881/

**Comment by cssmagic** [comment]
@yzpower 谢谢补充！
