### ISSUE TITLE
[BXT-015]《组件CSS样式接口设计》by 顾轶灵（E0）

### ISSUE THREAD

**Issue by hax** [baixing/BXT#20]
# 组件CSS样式接口设计

### 本期讲师

![e0 2x](https://user-images.githubusercontent.com/159840/38485321-e565697e-3c0b-11e8-91b9-5a72514c93a6.jpg)

顾轶灵， @Justineo ，网名 E0 或 10，百度资深前端研发工程师，[百度 EFE](https://github.com/ecomfe) 成员。活跃的开源贡献者，[Vue.js](https://github.com/vuejs) [核心团队成员](https://github.com/orgs/vuejs/people)。知乎 CSS、前端开发、JavaScript 话题的优秀回答者，[10万+大V](https://www.zhihu.com/people/justineo/followers)。

### 本期主题

组件化开发目前已经成为 Web 开发的主流，如何设计接口简洁且易于扩展的可复用组件就变得愈发重要。在组件框架领域的诸多挑战中，如何实现和定制组件的样式，也许是最具分歧的问题。从 CSS 预处理器到各种 CSS 方法论，从纯 CSS 到各种 CSS-in-JS 方案，无论理论还是实践，均呈百花齐放百家争鸣之态。CSS 本是针对“文档”的样式和排版语言，但现在我们必须从“组件”API 的角度重新思考。本次分享将深入探讨组件样式层接口的各种可能性，并通过 API 的三个层次（Internal、External、Interoperability）来检视不同方案在封装和扩展之间的取舍和平衡。

### 具体安排

- 时间：2018 年 4 月 17 日（周二） 19:30～21:30
- 地点：上海市徐汇区·上海交通大学·浩然高科技大厦
- 参加对象：Web 前端工程师
- 活动名额：60 人

### 报名

报名链接：http://www.hdb.com/party/zkx62.html

直播地址：https://www.douyu.com/hax

**Comment by yanhaijing** [comment]
期待，求直播

**Comment by fEyebrow** [comment]
演讲内容是不是和css大会上相似，讲题相似？有直播吗？

**Comment by hax** [comment]
@FourEyebrowXiake 主题是一样的，但CSSConf只有40分钟，本次活动有3倍的时间可以讲得更深入。另外我们会尽量安排直播。

**Comment by tounks** [comment]
观战直播

**Comment by ulivz** [comment]
哇，兄弟企业的活动，要来看看
