### ISSUE TITLE
[BXT-016]《前端生产环境部署 ES6+ 代码》by 邓钢（米粽）

### ISSUE THREAD

**Issue by hax** [baixing/BXT#22]
# 前端生产环境部署 ES6+ 代码

### 本期讲师

![myst729](https://avatars3.githubusercontent.com/u/519733)

邓钢， @myst729 ，饿了么前端架构师，网名「米粽」，人称亚洲贾伯斯。同性交友网和爆栈网玩家（Reputation top 4%），翻译过[几本卖得不太好的技术图书](https://www.douban.com/search?cat=1001&q=%E9%82%93+%E9%92%A2)。因为被禁言，所以不玩微博和知乎。在盛大创新院、IBM 中国开发中心都写过 bug。

### 本期主题

相比十年前发布的 ECMAScript 5，ECMAScript 2015（ES6） 有着巨大改进。随着主流浏览器的不断更新，ES6 规范乃至 ES7、ES8 的支持程度已经相当高了。这是不是意味着时机已经成熟，可以把 ES6+ 代码推向生产环境，让用户享受 ECMAScript 演化带来的体验提升？本次分享将探讨在前端生产环境部署 ES6+ 代码的实施方案、面临的问题和应对措施。

### 具体安排

- 时间：2018 年 5 月 16 日（周三） 19:30～21:30
- 地点：上海市徐汇区·上海交通大学·浩然高科技大厦
- 参加对象：Web 前端工程师
- 活动名额：60 人

### 报名

链接：http://www.hdb.com/party/88py2.html

### 直播

斗鱼：https://www.douyu.com/hax

**Comment by Lellansin** [comment]
前排围观 😃

**Comment by hax** [comment]
直播网址：https://www.douyu.com/hax

**Comment by fEyebrow** [comment]
直播没画面
