### ISSUE TITLE
[BXT-002] 《ELE.ME 是如何运行的》 by Sofish

### ISSUE THREAD

**Issue by zpbx** [baixing/BXT#3]
# ELE.ME 是如何运行的
### 本期讲师

[![avatar](https://cloud.githubusercontent.com/assets/5830104/9876614/f3a1a9da-5be9-11e5-9bb6-4bdc5529b411.jpg)](https://github.com/sofish)

林建锋 (@sofish)
- 饿了么资深前端架构师兼大前端团队负责人
- 曾就职于支付宝、百姓网
- 多个流行开源项目（Pen Editor、Typo.css、AliceUI、Puerh 等）的作者

（ [微博](http://weibo.com/isofish) &nbsp;|&nbsp; [GitHub](https://github.com/sofish) ）
### 本期演讲简介

前端方面 Ele.me 算是比较激进的团队，在面向大众产品中，包括桌面端、移动端，深度使用 SPA、SVG、ES6 等技术；组件式开发、自动化构建，甚至利用 Nginx 层解决前端一些硬伤，更极端到整个服务器/虚拟机上只有一个 HTML 文件，并做到 99.99% 可用的前端。

同时，发布/回滚速度（包含编译）只需要 100s 发布到全部生产环境机器，供快速响应、迭代。

这一年多来，我们遇到了什么？解决了什么？想跟大家分享一下。
### 本期具体安排
- 时间：2015年9月24日（周四） 晚7:30
- 地点：上海市徐汇区交通大学内
- 参加对象：对前端感兴趣的工程师们
- 活动名额：50人

---
### 本期幻灯片
- [[幻灯片] ELE.ME 是如何运行的](http://www.stuq.org/ppt/show/373/06ce3c23d0c94467b626c70c50ac20dc) （鸣谢 QCon 2015 上海站）

**Comment by zpbx** [comment]
## 本期 Demo 时间

### Tern：JavsScript 代码补全引擎

> by 维杰 (@jswh)
- [Tern 官网](http://ternjs.net/)（项目名意为“燕鸥”）
- 演示 - WebStorm 等 IDE 做不到的事
- 原理
- 主流编辑器插件

**Comment by jswh** [comment]
这是什么？

在 15/11/4，Zhang Peng<notifications@github.com> 写道：
> ## 本期 Demo 时间
>
> ### Tern：JavsScript 代码补全引擎
>
>> by 维杰 (@jswh)
>
> * [Tern 官网](http://ternjs.net/)（项目名意为“燕鸥”）
> * 演示 - WebStorm 等 IDE 做不到的事
> * 原理
> * 主流编辑器插件
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/baixing/BXT/issues/3#issuecomment-153593643


-- 
曹维杰
15317238403
