### ISSUE TITLE
[BXT-003] 《移动开发协作及性能优化案例》 by 赵世婚

### ISSUE THREAD

**Issue by zpbx** [baixing/BXT#4]
# 移动开发协作及性能优化案例

### 本期讲师

![avatar](https://cloud.githubusercontent.com/assets/5830104/10930966/4b2f9e92-82fe-11e5-8f8f-5119aa39ccae.png)

赵世婚

* 目前在沪江前端研发团队主要负责客户端基础架构（Android为主）。
* 此前在猎豹移动负责手机猎豹浏览器架构设计与研发。
* 喜欢关注前沿技术，参加技术沙龙分享技术，对移动客户端架构有深刻的理解，在移动 Native 与移动 Web 跨平台有深入研究与实践。

### 本期演讲简介

移动开发需要面对多方的协作，比如产品 UX、Web 前后端的协作等等。那么问题来了，需求变更、联调开发、项目进度所带来的压力，是否会让我们失去移动开发的乐趣？是否会让我们忽略用户体验及稳定性？本次分享将以实际案例对此作出解答。

### 本期具体安排

* 时间：2015年11月10日（周二） 晚7:30
* 地点：上海市徐汇区交通大学内
* 参加对象：移动开发工程师
* 活动名额：50人

***

### 本期幻灯片

* [[幻灯片] 移动开发协作及性能优化案例](https://github.com/baixing/BXT/raw/master/slides/bxt-003.pdf) （点击下载）

**Comment by happydog-intj** [comment]
RxJava我这里有整理了一份资料，欢迎大家来补充[https://github.com/lzyzsd/Awesome-RxJava](https://github.com/lzyzsd/Awesome-RxJava)
