### ISSUE TITLE
[BXT-006] 《如何看待 left-pad 事件》 by 贺师俊（Hax）

### ISSUE THREAD

**Issue by zpbx** [baixing/BXT#7]
# 如何看待 left-pad 事件
### 本期讲师

![avatar](https://cloud.githubusercontent.com/assets/5830104/15106449/05f5b55a-15fc-11e6-9218-557db24c5b45.jpg)

贺师俊（Hax）

百姓网前端工程师。
### 本期主题

最近的 left-pad 事件引发了众多讨论，甚至行为艺术。本次分享将真正严肃地探讨这一事件及其揭示的问题，包括但不限于：
- 谁是这次事件的罪魁祸首？azer？kik 公司？npm 公司？
- azer 是英雄还是熊孩子？
- npm 公司是不是邪恶的公司？
- 包是不是应该有命名空间？
- 我们都忘记怎么编程了吗？
- 小模块是好是坏？
- left-pad 本身应该怎么实现？
- 第三方依赖是好是坏？
- 是不是应该使用 shrinkwrap/lock（锁定依赖）？
- 是不是应该使用 bundle/pack（打包依赖）?
- 是不是应该自建仓库？
- JS/Node.js/npm/前端……的生态是不是有问题？

届时也欢迎大家参与讨论。
### 本期具体安排
- 时间：2016 年 5 月 11 日（周三） 晚 7:30～9:00
- 地点：上海市徐汇区交通大学内
- 参加对象：工程师
- 活动名额：50 人

---
### 本期幻灯片
- [幻灯片](http://johnhax.net/2016/all-about-left-pad/slide?qcon)
- [文字实录](https://mp.weixin.qq.com/s?__biz=MzIzMzEzODYwOA==&mid=2665284413&idx=1&sn=22c0f343e63fd2e2bf36a621f41c280f)
### 本期视频
- [Part 1](http://v.youku.com/v_show/id_XMTU2NzA1MzUxNg==.html)
- [Part 2](http://v.youku.com/v_show/id_XMTU2NzA1NTYxMg==.html)

**Comment by ShiningRay** [comment]
怎么报名？

**Comment by zpbx** [comment]
已在原文添加详细的报名方式 😃

**Comment by chaoren1641** [comment]
都是好问题，赞
