### ISSUE TITLE
[BXT-007] 《打造统一的全端团队》 by 郭达峰

### ISSUE THREAD

**Issue by zpbx** [baixing/BXT#8]
# 打造统一的全端团队

### 本期讲师

![avatar](https://cloud.githubusercontent.com/assets/5830104/17470032/a19e132e-5d6b-11e6-9d6f-76a5d02858b5.jpg)

**郭达峰**

Strikingly.com 和 sxl.cn 的联合创始人、CTO。

2011 年毕业于香港中文大学计算机专业，从 14 岁开始计算机编程。在创业之前，曾开发了数款用户数超过 2000 万的 Facebook App。

2012 年创立了 Strikingly —— 一个方便易用、并能在移动端使用的建站工具，并成为第一家进入 YC 孵化器的华人团队。最近 Strikingly 的中国版 “上线了”（sxl.cn）也上线了。

### 本期主题

《打造统一的全端团队》
(Building a Unified Frontend and Mobile Team)

移动开发者一直期望能把 Web 的开发体验带到原生应用开发中，比如 Codova/Ionic 就是这个方向的尝试。React Native 算是这股趋势里的新兴力量。它保留了 Web 开发体验的同时，也依然保证了原生组件的渲染性能。React Native 的出现也让更多的前端开发者可以有机会跨出 Web 做原生应用的开发。

本次 BXT 就和大家分享一些团队使用 React Native 的经验，并谈谈 Strikingly/上线了搭建全端团队的实践。

### 本期具体安排

* 时间：2016 年 8 月 11 日（周四） 晚 7:30～9:00
* 地点：上海市徐汇区交通大学内
* 参加对象：工程师
* 活动名额：50 人

***

### 本期幻灯片

* [[幻灯片] 打造统一的全端团队](https://github.com/dfguo/talks/raw/master/ningjs2016/unified-client.pdf) （点击下载）

**Comment by anthonyli** [comment]
PPT呢！！！

**Comment by zpbx** [comment]
幻灯片会在十月底公布，目前仍在保密期，请谅解 😉

**Comment by tolerious** [comment]
现在到了11月底了。

**Comment by cssmagic** [comment]
幻灯片已更新 😃
